
search_repos:
  end_condition: 'Maintained'
  end_value: 200
  from_year: '2011'
  to_year: '2019'
  partial_upload_size: 10

  unmaintained_ids: 'unmaintained_ids.dat'
  maintained_ids: 'maintained_ids.dat'
  not_suitable_ids: 'not_suitable_ids.dat'

compute_features:
  features: 'configs/features.yml'
  partial_upload_size: 10
  unmaintained:
    csv_file: 'unmaintained.csv'
    ids_file: 'unmaintained_ids.dat'
  maintained:
    csv_file: 'maintained.csv'
    ids_file: 'maintained_ids.dat'

s3_handling:
  file_name_prefix: 'samuelmacko-thesis/'
  region: 'us-west-2'

logger:
  file: 'event_log.log'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
